logger:
  console: true
  format_json: false
  level: debug

database:
  mysql:
    db_name: jsin
    db_host: mysql
    db_port: 3306
    username: root
    password: password
    conn_count: 27
    conn_idle_time_sec: 7
    conn_life_time_sec: 2000
    options: parseTime=true

external:
  s3:
    cloudflare:
      bucket: jsin
      uri: cloudflare_uro
      accountId: account_id
      token: token
      access_key_id: access_key_id
      secret_access_key: secret_access_key
      jurisdiction_specific: r2_url
#  Fetch images from custom 3rd parties
  custom_3rd_parties:
    parties:
      - url: "url"
        json_key: "map key to find img url"
        method: GET
        header: api-key
        token: token
    command: custom-command

telegram_bot:
  token: bot_token
  debug: false
  offset: 0
  timeout: 60
  create_cronjob_command_content: |
    j.sin will send you random gift
  cronjob_image_caption: |
    A picture a day keeps the doctor away

# you can explain your image type here
help_command_content: |
  j.sin to generate content
