server:
  http:
    host: localhost
    port: 10080
  apiKey: 'key'

logger:
  console: true
  format_json: false
  level: debug

database:
  mysql:
    db_name: jsin
    db_host: mysql
    db_port: 3306
    username: root
    password: password
    conn_count: 27
    conn_idle_time_sec: 7
    conn_life_time_sec: 2000
    options: parseTime=true

external:
  s3:
    cloudflare:
      bucket: jsin
      uri: cloudflare_uro
      accountId: account_id
      token: token
      access_key_id: access_key_id
      secret_access_key: secret_access_key
      jurisdiction_specific: something

telegram_bot:
  token: bot_token
  debug: false
  offset: 0
  timeout: 60
