name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - "**.md"

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      IMAGE_TAG: ${{ steps.tag.outputs.value }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Store git tag value to output
        id: tag
        run: echo "value=$(git describe --tags --always --abbrev=7)" >> $GITHUB_OUTPUT

  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login dockerhub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Build the Docker image
        run: docker build -t jsin .
      - name: Tagging image
        run: docker tag jsin:latest hvn21/jsin:${{ needs.setup.outputs.IMAGE_TAG }}
      - name: Push Dockerhub
        run:  docker push hvn21/jsin:${{ needs.setup.outputs.IMAGE_TAG }}

  dispatch:
    needs: [ build, setup ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Workflow Dispatch
        uses: benc-uk/workflow-dispatch@v1
        with:
          repo: ${{ secrets.CONFIG_REPO }}
          token: ${{ secrets.REPO_ACCESS_PAT }}
          workflow: pull image tag
          ref: main
          inputs: '{"image_tag":"${{ needs.setup.outputs.IMAGE_TAG }}", "commit_url": "${{ github.event.head_commit.url }}"}'
            
